"""Create users and related tables

Revision ID: 776838d38af9
Revises: 
Create Date: 2024-09-03 14:55:45.657952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776838d38af9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('main_emotion', sa.String(length=50), nullable=True),
    sa.Column('main_emotion_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotion_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('emotion_name', sa.String(length=50), nullable=True),
    sa.Column('emotion_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diary_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotion_reports')
    op.drop_table('diary_entries')
    op.drop_table('users')
    # ### end Alembic commands ###
